apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mirror-registry-k8s-io
  namespace: cyclops-assets
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: cyclops-fs
  volumeMode: Filesystem
