apiVersion: v1
kind: ConfigMap
metadata:
  name: mirror-registry-k8s-io
  namespace: cyclops-assets
data:
  config.yml: |
    version: 0.1
    delete:
      enabled: true
    http:
      addr: :5000
      h2c:
        enabled: true
      headers:
        X-Content-Type-Options: [nosniff]
      http2:
        disabled: false
    log:
      accesslog:
        disabled: true
      fields:
        service: registry
      formatter: json
    proxy:
      remoteurl: "https://registry.k8s.io"
      ttl: 336h0m0s
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
