apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: squid-state
  namespace: cyclops-assets
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: cyclops-fs
  volumeMode: Filesystem
